# Note: nfs-client storage class is already managed by nfs-subdir-external-provisioner
# and is excluded from Fleet management to avoid conflicts

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fast-scratch
provisioner: rancher.io/local-path
parameters:
  nodePath: /mnt/nvme/scratch
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: false
