apiVersion: v1
kind: ServiceAccount
metadata:
  name: juju-toolbox-sa
  namespace: vcluster-ckf
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: juju-toolbox-role
  namespace: vcluster-ckf
rules:
  - apiGroups: ["apps"]
    resources: ["statefulsets", "deployments"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods/portforward"]
    verbs: ["create"]
  - apiGroups: [""]
    resources: ["services", "secrets", "pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: juju-toolbox-rb
  namespace: vcluster-ckf
subjects:
  - kind: ServiceAccount
    name: juju-toolbox-sa
    namespace: vcluster-ckf
roleRef:
  kind: Role
  name: juju-toolbox-role
  apiGroup: rbac.authorization.k8s.io
