{{- if .Values.ssh.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "jupyterhub-ssh.ssh.fullname" . }}
  labels:
    {{- include "jupyterhub-ssh.ssh.labels" . | nindent 4 }}
    {{- with .Values.ssh.serviceLabels }}
    {{- . | toYaml | nindent 4 }}
    {{- end }}
  {{- with .Values.ssh.serviceAnnotations }}
  annotations:
    {{- . | toYaml | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.ssh.service.type }}
  ports:
    - name: ssh
      port: {{ .Values.ssh.service.port }}
      targetPort: ssh
      protocol: TCP
      {{- if eq .Values.ssh.service.type "NodePort" }}
      nodePort: {{ .Values.ssh.service.nodePort }}
      {{- end }}
      # A "sftp" port (2222 -> targetPort: sftp) was removed here 2026-07-06
      # -- see ../ssh/deployment.yaml's comment. Nothing in this Deployment
      # ever listened on it.
  selector:
    {{- include "jupyterhub-ssh.ssh.selectorLabels" . | nindent 4 }}
{{- end }}
