{
 "title": "NVIDIA GPU Monitoring - Overview",
 "description": "This Grafana dashboard uses the NVIDIA DCGM exporter to monitor GPU performance in Kubernetes clusters. Supporting both MIG and non-MIG GPUs, it provides real-time metrics on utilization, memory, temperature, power, and more, enabling efficient management of NVIDIA GPU resources.",
 "tags": [
  "gpu",
  "kubernetes-mixin",
  "MIG"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Hostname",
    "query": {}
   },
   {
    "name": "gpu",
    "label": "GPU ID",
    "query": {}
   },
   {
    "name": "mig",
    "label": "GPU Device",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Aggregate", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "GPU Engine Utilization",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * avg (DCGM_FI_PROF_GR_ENGINE_ACTIVE)"
    }
   ]
  },
  {
   "title": "Tensor Core Utilization",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * avg (DCGM_FI_PROF_PIPE_TENSOR_ACTIVE)"
    }
   ]
  },
  {
   "title": "GPU Memory Bandwidth Utilization",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * avg (DCGM_FI_PROF_DRAM_ACTIVE)"
    }
   ]
  },
  {
   "title": "GPU Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum (DCGM_FI_DEV_FB_USED)" },
    {
     "expr": "sum (DCGM_FI_DEV_FB_USED) + sum (DCGM_FI_DEV_FB_FREE)",
     "legendFormat": "total"
    }
   ]
  }
 ]
}