apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: grafana-admin-credentials
    namespace: cattle-monitoring-system
spec:
    secretTemplates:
        - name: grafana-admin-credentials
          stringData:
            admin-user: ENC[AES256_GCM,data:Cp0X/k8=,iv:YaeZ+2SBNRz7pMx6bR5FPB6sCq7yaGo6aSHfgpej/wg=,tag:2yB2NVsyiCAbGP9u/SXhPA==,type:str]
            admin-password: ENC[AES256_GCM,data:6CRkBSchjoJcDJW5Z2Yc8SkI5Z8kAqr1EJkj8m/yYgg=,iv:MEff+hk9wfeBeWFLMtcW+TiBu8pTammkX0DDcN8IF9E=,tag:GvVrhtuVqLalZYFu0KFifg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXVzNkSE1iUUluNUZubmZu
            WkkzNzNLejhrYmNvYXhUNVJkcEtBR25XbFZnCmtzbDRIbW9wNDF4ZFpNcUpCMFpt
            VzNHM3pDMHdTYXFnL1Y1cGZkSmpndkEKLS0tIERoRlNRUlQ0TzJwVXQ1NURHNWFT
            azZWSitaUm9OVURsOGhGNkdhWlh3RTgKORugsGD7uSakrHixMHKBUf+0nJbKtglT
            ueBcpXFGsI5GtDksbtoW6NlO64QFJhyHIuhu7uk6E0ljFyP8XXoSEQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h05qj66un22scwapuhyl76skls7ll235vlu27cjwkk5tpav6sqmsx3zp6a
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-07-23T08:27:04Z"
    mac: ENC[AES256_GCM,data:mnzSowIfhz6QwicculggABiZT5Zbe9DECIWje1uWWszybXKCVHXYRjGXvPVoB+jCcIeAWpU7pjy9aekLMKEKEaLtOv+oqpHGllCeZwBhikxqIIrK8zsJQW5O5WeuKpBpWVygVrdaQgig+pK2CJGRBCoYCsj/FnBPlN57UezzL30=,iv:IIURzJ3I3vlbD14ZRR56Kz/JeEzc0EEPVklwRJ9+eVM=,tag:djsCpougVmaHW4IDP7rUsw==,type:str]
    version: 3.13.3
