apiVersion: v1
kind: Secret
metadata:
  name: open-webui-oidc
  namespace: ai-llm
type: Opaque
stringData:
  # TODO: Replace with actual OIDC credentials
  OAUTH_CLIENT_ID: "5PLqeFpglsR0YVcsZj6nQtBkzNG6EiGyjQOZAdGr"
  OAUTH_CLIENT_SECRET: "E3lYRE1jb1dScAvUZwOCdyXZ39tQCxE9KSxeQhAf2VqMUQ23LnQgF7THuEh1z24DMLouzds7rvJA3aRFP6ExniEgQvP9oA87rcpFmb1NDYwKX7ilxsQg2bNNq1NhlvOu"
  OPENID_PROVIDER_URL: "https://auth.cps.unileoben.ac.at/application/o/open-web-ui/.well-known/openid-configuration"
