apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: gha-runner-splatograph-config
    namespace: arc-runners
spec:
    secretTemplates:
        - name: gha-runner-splatograph-config
          stringData:
            github_token: ENC[AES256_GCM,data:nKyXV3SnEYZGOUss5uz82eyTEeJ6ydtk7vZe9mBNkxn+/czjpRrgSw==,iv:Cy0UinQJ7cO2K67MDDmwFd0ZJ/uxbNI2G5wU73hMieY=,tag:h0VYpHHcKKToIlCg56yRzQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXSW9JdFM5Wmw0MGpoZE95
            ekFQZGNBSjhSZ1hYU2VKdXQwK1VKY2lKL3lFCkxtUm9sdDh4a2Q5K3E2Uk5BWFNt
            TURRMldMSFNTblBQTHdoMXh6c2NSSHMKLS0tIHZ5ekJBbnF3cTJ3RE9NaGF6OE40
            Um85NnY4MFdwZGJWU2ViaFo1SWc2Z0kKMaWhxCyyYt/8ui341/rIOpijaq4PgeUA
            t0ez17vFi2r6o4oQLCyaGtejZ5NySDnE7zsK1y7KkqCJKtuwvE/ccQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h05qj66un22scwapuhyl76skls7ll235vlu27cjwkk5tpav6sqmsx3zp6a
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-08-25T17:59:18Z"
    mac: ENC[AES256_GCM,data:rJDpMt1Iztvgr+4bzjl+uaCI1ck2/vnQg+PySXKOCv6+bt6TUbuOQJjPzX1lqxRdMsbStSEuOZ5PNdflirkLrDDBfe/5eU0GAJTvoMVDRnluSY2jpizv94dYgIEA8m8yCNsH0QUO4eo7JtjixmkGie4MS6QAnNqx4juYvSHNTTI=,iv:OEGHxln9wVcRhd2GsrmbbGQ1/4rTScma1bTDdJArglw=,tag:LdscqlFRjIPLKpYvWwrPrQ==,type:str]
    version: 3.13.3
