apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: gha-runner-splatograph-config
    namespace: arc-runners
spec:
    secretTemplates:
        - name: gha-runner-splatograph-config
          stringData:
            github_token: ENC[AES256_GCM,data:38IQfNGzwn9489jL0gXDdyig5PgAHbNoMzMBKHI0q2flsvrevLeUZ1W3e/uJbqvD21q94IS5VKINgJnQ59Cm1LX1zI4OqixYMykDYWqOOXXyaHDHbeEJPvUQPL0I,iv:N4DD3QZ5Xv3PoDAx1KXUUITlzoteAa/jtootcl1aCAc=,tag:6FKDOCXUY2yfmbkZ/UQZ3A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2VmZ4aTgwbzBiaWtrOFQw
            c0IxZEpjVE9ZczFVM3hVOE1LNzZSWFU5ZlVzCnYvSlBsWnNYRmhwMmx3b01TSFV6
            aTN1WGpCTmoxZ2s5dEl5bXFleS9NMGcKLS0tIGxsTjNvbDhGNkRJRTBaUXFSclMx
            cmgrYXRheEN2WG1PbXZHZGJtcDROT2MKe4tUM7PgJUZuI0iv18UBrpjyOMvV4NDq
            3E+erAf8dG9jfSYz911R/XYdXTv3jvdiwiFj/Ax2Y1B/2slBEtdbUA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h05qj66un22scwapuhyl76skls7ll235vlu27cjwkk5tpav6sqmsx3zp6a
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-07-26T12:13:00Z"
    mac: ENC[AES256_GCM,data:+cZByQcQTaVLzwPCQMMt7yAdyJBM/DAnU6WNowNyUgX688XI94ect0AWCIof6WvKrT/8eXyArE05K+Staq4YD4E9Qngrw2TfwNSMDkkG8GdNg0rYDkAgOOiVs85rW4iik83i3PM3lOok/jptIFxrjFJtUpTjVwUV55WBtMD0Gvs=,iv:y5eByYN7FPdQ11S7Qk18bADt+RVFXtYADXarU2dcDMU=,tag:mEimWUfOK0QtE3Nb7yzGmA==,type:str]
    version: 3.13.3
