# vcluster.yaml structure
# Docs: https://www.vcluster.com/docs/vcluster/configure/vcluster-yaml/

# 1. Disable syncing StorageClasses from host (we manage them manually to control default)
sync:
  fromHost:
    storageClasses:
      enabled: true
    nodes:
      enabled: true # for gpu support?

# # 2. Disable internal k3s local-path provisioner
# controlPlane:
#   distro:
#     k3s:
#       enabled: true
#       extraArgs:
#         - "--disable=local-storage"

# 3. Create 'longhorn' StorageClass inside vcluster and make it default
# init:
#   manifests:
#     charts:
#       - name: longhorn-sc
#         manifests: |-
#           apiVersion: storage.k8s.io/v1
#           kind: StorageClass
#           metadata:
#             name: longhorn
#             annotations:
#               storageclass.kubernetes.io/is-default-class: "true"
#           provisioner: driver.longhorn.io
#           reclaimPolicy: Delete
#           allowVolumeExpansion: true
#           volumeBindingMode: Immediate
#           parameters:
#             numberOfReplicas: "3"
#             staleReplicaTimeout: "30"
#             fsType: "ext4"
#             dataLocality: "disabled"
#             unmapMarkSnapChainRemoved: "ignored"
#             disableRevisionCounter: "true"
#             dataEngine: "v1"
#             backupTargetName: "default"

# Standard networking defaults
networking:
  advanced:
    proxyKubelets:
      byHostname: false
      byIP: false

# # Security defaults
# policies:
#   podSecurity:
#     enabled: false
