apiVersion: v1
kind: Pod
metadata:
  name: test-volume-attach
  namespace: jupyterhub
spec:
  containers:
  - name: test
    image: busybox
    command: ["sleep", "3600"]
    volumeMounts:
    - name: shared
      mountPath: /data
  volumes:
  - name: shared
    persistentVolumeClaim:
      claimName: jupyterhub-shared-storage
