---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: default-l2
  namespace: metallb-system
spec:
  ipAddressPools:
  - default-pool
  # Advertise on all interfaces
  # MetalLB will respond to ARP requests for allocated IPs
