apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: jupyterhub-ssh-gateway-token
    namespace: jupyterhub
spec:
    secretTemplates:
        - name: jupyterhub-ssh-gateway-token
          labels:
            app.kubernetes.io/name: jupyterhub-ssh
            app.kubernetes.io/component: ssh
          stringData:
            admin-api-token: ENC[AES256_GCM,data:XLezn4C4KRtdmodYa5MuGDigjbl5GfRgV0Lct7PE7F822OypFmeOO32kmvGqTOza7HwLBxkbPo7kpOhsEAIn7A==,iv:SwfVYPGjl/lCEcnaJnTcwnNALx1mK2+ZYcD7LKJDHpM=,tag:7LF79EaQvacu2FjpbX51fA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzZXl6MWhpM0l1M2hHVXpp
            WmdGdFA2MWR2ZjNZRExUcm1nOGQ3ZzlqVmpVCmhUSXpmZUZIeGE4dGlveDN1R1hR
            L3FSclY1SS9ZR1E2RFU0VHYvYzNoSzQKLS0tIHYwc2ZvZmFvZjZpU2JlUG1uVitK
            M2FYQ1M0RWt5SGZ3bzI0cHh3T1I0WHMKUJgy7ztqPWcDFxhnB24+M2AB+qt9FxDq
            NeOuvB+QpISKm9JEYu7UNIU1uPnaLRxOrqvNcmAJmmAEFTh/hHkZeg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h05qj66un22scwapuhyl76skls7ll235vlu27cjwkk5tpav6sqmsx3zp6a
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-08-04T08:41:36Z"
    mac: ENC[AES256_GCM,data:2sXBIVM0lZFieYEGV3KJVNLXC80yMqeb9Hr5mhz0tOGzHDKCZzljR0Z5BkGrbkWBtim/yn7DZbC251TWmlKdRGyFgxgrX9tPcI3YeNOUBzhpSrIy7mvPvVN8Wvbbviu86i4N4eaFTZ0aB4MdYmgsLgtVUjNoyLKa8YHTjSgB6/E=,iv:JKbH6n4Vla4EkOqDqwgZqrZ4Mq2PqqXux4K2FgRG0Mk=,tag:1SmFeiUCbzeOHoeTJ3fwLg==,type:str]
    version: 3.13.3
