enabled: true
suspend: false
owner: cps
namespace: jupyterhub
image: docker.io/library/postgres@sha256:866264fb97643e747f9d0981cd060114f83b49450e5bac4988324bb3c6af2fd7
host: postgresql.jupyterhub.svc.cluster.local
secretRef: postgresql-secret
passwordKey: postgres-password
userKey: postgres-user
databaseKey: postgres-db
databasePodLabels:
  app.kubernetes.io/component: database
  app.kubernetes.io/name: postgresql
