apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: ci-harbor-builder
    namespace: ci
spec:
    secretTemplates:
        - name: ci-harbor-builder
          type: kubernetes.io/dockerconfigjson
          stringData:
            .dockerconfigjson: ENC[AES256_GCM,data:f3q75rdGnW4YgCKlZFQxR4IyvwAZgR4uwlWOPCNIX7gMzc3C/1U6ZfIqovnbLKtHNanVLGw4YhmKvdPFWUeBJN5k8Zt7RlS5maRopveCSJ+0DlUBzLFlQYIJHlZvMM8ittpFs8In+gti/OpgG50eRkcbDh0N1zyjl/UO4LxHtC3abJu70lIVr/gvGB8NPtfml4euHicEE3zKMEpgH+ORtVkkp5Zbu9QvKGtW8HHPTijwUb2F5DOsYQ9AeGbWOfo51uYWs1WL,iv:agYNws2gnIo96d3XLrOygHfE+26MVxvPb35mMYrch/U=,tag:YfrqYiykJqH54m+VYxwXZg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzTGNYdVkvOGVxYk12b1BD
            anBHMENsZGZOSTk5T3RBbnlaRGZxZk5HT0YwCmRtK3lCMHdWa1gzMC8vamVMZnBh
            NWU2S0p5cG16ckZzQ25yMDNWSkdPQ1kKLS0tIHNCbjBZVnM1aTNaOGRNZkc2UlpF
            TW1PL2VJWTYxU2p5OW1xU2FMSm5nM0EKvu3oW6WYEAxiYeX92pjSIjQVcZgBZjxa
            OzH7bidvTr6cpOXrMOR4Gkvj2WiwZZKmomFBHB9xUcrAArdcwlxEzQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h05qj66un22scwapuhyl76skls7ll235vlu27cjwkk5tpav6sqmsx3zp6a
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-07-25T20:28:49Z"
    mac: ENC[AES256_GCM,data:G5ajlSc+D8XA/5NZkpRW/nQMmItXqjRxN7e+s2C/F6BBvzqhPIUK1muT8joG303ZZ4dpC0UaU/e6e50VR+syQGCyAMPfDVw5N5MPnWSNxCfm4YnX0rRUhsM+ojRReP1bqax6zom43vIxOqyK3QxqDIwbZ/DbfXtX1bKgGZUaeAM=,iv:qbQjS9n/Hs6HsFKRioU6Z+fctEkmKPlJTejOchyjuu4=,tag:0HfYSoG/eT9YB3SIUb2mrw==,type:str]
    version: 3.13.3
