apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-mig-parted-config
  namespace: gpu-operator
data:
  config.yaml: |
    version: v1
    mig-configs:
      all-disabled:
        - devices: all
          mig-enabled: false

      all-enabled:
        - devices: all
          mig-enabled: true
          mig-devices: {}

      # Custom profile for 1 MIG GPU and 1 Full GPU on a dual-GPU node
      one-mig-one-full:
        - devices: [0]
          mig-enabled: true
          mig-devices:
            "1g.5gb": 7
        - devices: [1]
          mig-enabled: false

      # Dynamic MIG presets for A100 40GB (applied to all GPUs on the node)
      a100-1g.5gb-7:
        - devices: all
          mig-enabled: true
          mig-devices:
            "1g.5gb": 7

      a100-1g.5gbx5-2g.10gbx1:
        - devices: all
          mig-enabled: true
          mig-devices:
            "1g.5gb": 5
            "2g.10gb": 1

      a100-1g.5gbx3-2g.10gbx2:
        - devices: all
          mig-enabled: true
          mig-devices:
            "1g.5gb": 3
            "2g.10gb": 2

      a100-1g.5gbx1-2g.10gbx3:
        - devices: all
          mig-enabled: true
          mig-devices:
            "1g.5gb": 1
            "2g.10gb": 3

      a100-1g.5gbx2-2g.10gbx1-3g.20gbx1:
        - devices: all
          mig-enabled: true
          mig-devices:
            "1g.5gb": 2
            "2g.10gb": 1
            "3g.20gb": 1

      a100-2g.10gbx2-3g.20gbx1:
        - devices: all
          mig-enabled: true
          mig-devices:
            "2g.10gb": 2
            "3g.20gb": 1

      a100-1g.5gbx3-3g.20gbx1:
        - devices: all
          mig-enabled: true
          mig-devices:
            "1g.5gb": 3
            "3g.20gb": 1

      a100-1g.5gbx1-2g.10gbx1-3g.20gbx1:
        - devices: all
          mig-enabled: true
          mig-devices:
            "1g.5gb": 1
            "2g.10gb": 1
            "3g.20gb": 1

      a100-3g.20gbx2:
        - devices: all
          mig-enabled: true
          mig-devices:
            "3g.20gb": 2

      a100-1g.5gbx3-4g.20gbx1:
        - devices: all
          mig-enabled: true
          mig-devices:
            "1g.5gb": 3
            "4g.20gb": 1

      a100-1g.5gbx1-2g.10gbx1-4g.20gbx1:
        - devices: all
          mig-enabled: true
          mig-devices:
            "1g.5gb": 1
            "2g.10gb": 1
            "4g.20gb": 1

      a100-7g.40gbx1:
        - devices: all
          mig-enabled: true
          mig-devices:
            "7g.40gb": 1
