hubUrl: http://proxy-public.jupyterhub.svc.cluster.local
ssh:
  enabled: true
  service:
    type: ClusterIP
sftp:
  enabled: true
  pvc:
    # Mount the shared RWX volume used inside singleuser as /home/jovyan/work/shared
    enabled: true
    name: jupyterhub-shared-storage
