apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cps-artifacts-relay
resources:
  - deployment.yaml
configMapGenerator:
  - name: artifacts-relay-proxy
    files: [haproxy.cfg]
