apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: beszel-data
  namespace: beszel
  labels:
    app.kubernetes.io/name: beszel
    app.kubernetes.io/component: hub
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
