apiVersion: v1
kind: ServiceAccount
metadata:
  name: cni-cleaner
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cni-cleaner
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cni-cleaner
subjects:
- kind: ServiceAccount
  name: cni-cleaner
  namespace: default
roleRef:
  kind: ClusterRole
  name: cni-cleaner
  apiGroup: rbac.authorization.k8s.io
