apiVersion: v1
kind: Pod
metadata:
  name: debug-cni-gpu2
  namespace: default
spec:
  nodeName: k3s-wk-gpu2
  hostNetwork: true
  containers:
  - name: debug
    image: alpine
    command: ["/bin/sh", "-c", "ls -la /host-cni-conf/ && sleep 3600"]
    volumeMounts:
    - name: cni-dir
      mountPath: /host-cni
    - name: cni-conf-dir
      mountPath: /host-cni-conf
    securityContext:
      privileged: true
  volumes:
  - name: cni-dir
    hostPath:
      path: /var/lib/cni
      type: Directory
  - name: cni-conf-dir
    hostPath:
      path: /var/lib/rancher/k3s/agent/etc/cni/net.d
      type: Directory
