apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: coder-pvc-manager
  namespace: coder
  labels:
    app.kubernetes.io/name: coder-pvc-manager
    app.kubernetes.io/component: rbac
    app.kubernetes.io/part-of: coder
rules:
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["create", "delete", "get", "list", "watch", "patch", "update"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: coder-pvc-manager-binding
  namespace: coder
  labels:
    app.kubernetes.io/name: coder-pvc-manager-binding
    app.kubernetes.io/component: rbac
    app.kubernetes.io/part-of: coder
subjects:
- kind: ServiceAccount
  name: coder
  namespace: coder
roleRef:
  kind: Role
  name: coder-pvc-manager
  apiGroup: rbac.authorization.k8s.io
