apiVersion: v1
kind: Secret
metadata:
  name: coder-oidc-secret
  namespace: coder
  labels:
    app.kubernetes.io/name: coder
    app.kubernetes.io/component: oidc-secret
type: Opaque
stringData:
  client-id: "lDBqyH9xujZ1WC1PCPPxiqIWg5o0FAX83UmQshsB"
  client-secret: "vRA9Z4ueEymKFxxQn3wHplxLRabUm0CFXHShJmEpmSjaXxhsdVwto2Q5m1RF7Bu2nyUULUIVEQhJM3Ix6xZdUqwnhnWz0geSgThZdPYKoxbAY8RhTEQ8JPyOVDh34wpt"
