apiVersion: v1
kind: Secret
metadata:
  name: coder-db-secret
  namespace: coder
  labels:
    app.kubernetes.io/name: coder
    app.kubernetes.io/component: database-secret
type: Opaque
stringData:
  # Connection URL for Coder
  url: "postgres://coder:coder-secure-db-password-2025@postgresql.coder.svc.cluster.local:5432/coder?sslmode=disable"
  # Individual fields for PostgreSQL container
  postgres-password: "coder-secure-db-password-2025"
  postgres-user: "coder"
  postgres-db: "coder"
