apiVersion: v1
kind: Secret
metadata:
  name: coder-db-url
  namespace: coder
  labels:
    app.kubernetes.io/name: coder
    app.kubernetes.io/component: database-secret
type: Opaque
stringData:
  url: "postgres://coder:coder-secure-db-password-2025@postgresql.coder.svc.cluster.local:5432/coder?sslmode=disable"
