apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  coder.db: |
    $ORIGIN coder.dshl.unileoben.ac.at.
    $TTL 60
    @ IN SOA ns.coder.dshl.unileoben.ac.at. admin.coder.dshl.unileoben.ac.at. (
        2025011501 ; serial
        3600       ; refresh
        900        ; retry
        604800     ; expire
        60         ; minimum
    )
    @ IN A 10.21.0.50
    * IN A 10.21.0.50
  coder.server: |
    coder.dshl.unileoben.ac.at {
        file /etc/coredns/custom/coder.db
    }
