apiVersion: http.keda.sh/v1alpha1
kind: HTTPScaledObject
metadata:
  name: ollama-http
  namespace: ai-llm
spec:
  hosts:
    - ollama-http.ai-llm.svc.cluster.local
  pathPrefixes:
    - /
  targetPendingRequests: 50
  scaleTargetRef:
    name: ollama
    service: ollama
    port: 11434
  replicas:
    min: 0
    max: 1
  scaledownPeriod: 120
