apiVersion: http.keda.sh/v1alpha1
kind: HTTPScaledObject
metadata:
  name: ollama-http
  namespace: ai-llm
spec:
  hosts:
    - ollama-http.ai-llm.svc.cluster.local
    - ollama-http.ai-llm.svc.cluster.local:8080
    - ollama-http
    - ollama-http:8080
  pathPrefixes:
    - /
  targetPendingRequests: 1
  scaleTargetRef:
    name: ollama
    service: ollama
    port: 11434
  replicas:
    min: 0
    max: 1
  scaledownPeriod: 300
