apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: jupyterhub-ldap-credentials
    namespace: jupyterhub
spec:
    secretTemplates:
        - name: jupyterhub-ldap-credentials
          labels:
            app.kubernetes.io/name: jupyterhub
            app.kubernetes.io/component: ldap
          stringData:
            bind-password: ENC[AES256_GCM,data:quF50ofYlUI4edE=,iv:qcF2GQJZZPG2DzTdBVaf7U+CD2S8kfLcmVxCIbL9NKU=,tag:FIVYrV928woP6Is9gkS6Bg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJcHh4L1ZCQVd5NU80M3RW
            dUN5a0owQjBLZS85WnJ4ZEtUdnEyS0xVUjJrCjBCRjVZRmllcG1UZG02WFMvYzJh
            SWVvbGhrYTlvQVV5YitrYm5TU3lqbzgKLS0tIDgycnh6OHNRVUx1OHNPclhWTDRp
            YXBOQ1RLTDQ4S2ozWlJvaWJoazFNSlEKNgG+FC8A0OMfasUr+dlR/VaoN2N0exRQ
            U9SZY4WzT+igpLBk5eZkPlhfcOGKkowfLe7aoYu7gNMtfPoBSuJSbQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h05qj66un22scwapuhyl76skls7ll235vlu27cjwkk5tpav6sqmsx3zp6a
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-07-23T08:36:54Z"
    mac: ENC[AES256_GCM,data:8aW2jo4xwNgeePg28NoFm8Secmx2+ytn3roOt5zYbxJRVJNQ+/CgYavDVK/u8OKBhcbzqJyJk7ZBJarNZrTmpZMoJS81zTqniBAWbmBCl1AJVr2kNHlvtW+/3QrefpHcPFhYfwvSIEAg5NZlwZoDSUfLqRXJJ4CPe3gVNhn4gMg=,iv:7OwESKvW5D/ifhz39coLd8+k5RmKyyXtx29Yp/Hkz+M=,tag:8SEqJBZBcR0jcSBFAsoq4Q==,type:str]
    version: 3.13.3
