apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: jupyterhub-oauth-secret
    namespace: jupyterhub
spec:
    secretTemplates:
        - name: jupyterhub-oauth-secret
          stringData:
            client-secret: ENC[AES256_GCM,data:053ADIxcKE4IVC83rfOBdFlVPqE5BPa4r5KUebaNNun8l0raZNqA55STrzDxMnFAGsagGJduIpgAZOx3P47c7zbI/uQqp6hZK2/rTtLuL9T6TCfGTj9TdrLMBAkoRLvFimv3UGOOftnBgxGCxBcRhoNrvHTC3EoIOFa2otSh,iv:5/LMVpwl301a0ny3SHqBXrrpp4nNjFgTSE1x7e9eTcA=,tag:O3JDivjHTVTfUmrT5FgyLA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBncTgyNGppRmVLT0x3UkJI
            NWdaZlQraWFuaGFjR05qUStWVW4zR2pIOUhJCi9RWkM2UTE3ZVd1d3ZsMm5kTVNn
            ZmxaTC9nQ25Rakk4cUNMY0RVMHpXR00KLS0tIFJ4NHNzRlMyOGdrZm5BWWRkYzJy
            VStDcmRXT2F1M29FTWFScCtvM2dJOVEKMhd/MzTpae6JGo1+RXo4CeJLZYDeESkZ
            6Av+6d7AdprHEtGG45k62MkuQJ5Biz2bxCJL+fVwRchuBSTPOPl2mA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h05qj66un22scwapuhyl76skls7ll235vlu27cjwkk5tpav6sqmsx3zp6a
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-07-23T09:57:36Z"
    mac: ENC[AES256_GCM,data:7TUdhvkeqMKGgx9GuIkMiJrJWzmq7RULxjiVPgktUgPFRAOlWP6rUT1bSsP7d77Q4+DOIHCVomnIhyh6YC9f+JgaoagDxp9P9DMqOmyry9l11wyGHMgM/xZ1jgtuidmDpgwJzDTxLq6/gL+sbMNfz49sUdNzQ+Xhe7dE22ocSVQ=,iv:+Y51rzuY0l5GIY/JU2NH9nIrAzBF6dYyxinF2UiKdPA=,tag:7ZUM3BSwuJUcuF3z2c3PZQ==,type:str]
    version: 3.13.3
