apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: jupyterhub-oauth-secret
    namespace: jupyterhub
spec:
    secretTemplates:
        - name: jupyterhub-oauth-secret
          stringData:
            client-secret: ENC[AES256_GCM,data:Kk2MfNR+F0l/Pny8MCXHQNeP1WSYA8m/3M69YXSwOSUaSLs0Pp+rlhkOKPwkl3MPPCAopItztl/REsHhuVzc+AGmTdfs8OmH6k6+eNFmqVXNwiNYym9EOXJkLX1XpZwVOcB1Y4OY6xEWMgjudgeEADIIIYiAvRrZei49iMqMGV0=,iv:FwyaCpOhNtKh6d1TDm3WuFS8bLI9Y5c/mxQhhaRA7r0=,tag:HON4Nq5ccVK7M/LuXkPdDg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXRDBUSU03S1dCNVhRTG5X
            MHovWk1sYmhhN2p1alZqVUdDZjRtUmJBYjFRCmFlY2ZDNjNjTGQyWVVkdTMxcVV0
            ajFreHpXTUhKTDlFRUdoOFZJNW5rOG8KLS0tIFNvamVFQnJQNFRmK0ZvcFllWHRk
            dWlQYnZRdTFPUjA1bjFhY0pXejQySVkK0rw9LheWCLeIozDM+T9xNVxdj6QJBiFG
            oruDdQZfdssVeP8N3dUu+EqYVz+6GGgcwcIf/6PMCWp4Sr49vzcmDw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h05qj66un22scwapuhyl76skls7ll235vlu27cjwkk5tpav6sqmsx3zp6a
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-07-23T09:13:36Z"
    mac: ENC[AES256_GCM,data:i/MJnodQQPPy+3H2YzUBvl5uGGi3V24dzNAouborf3W2lxbLEoyDdOgC0NrFRjfScptxbzSyIderyKFROCrhglpQe1rn7wLLMxZWLHgaxLPiqKs8hms/UI8wLBJFifamQCKOzFrAHD3iZktK7T2iyaCrcc2HA/4hntEvwdeT4Tk=,iv:NfTgmlTV6WHSWovaNR7Aosank1I7tReGQPt3/hZboi0=,tag:agcUEaNh5D/rL5HMKn8Guw==,type:str]
    version: 3.13.3
