apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: jupyterhub-oauth-secret
    namespace: jupyterhub
spec:
    secretTemplates:
        - name: jupyterhub-oauth-secret
          stringData:
            client-secret: ENC[AES256_GCM,data:XUaEaZNxoQ5leRFkT+6hYiNYCMj5Qyw2jp/Hxxp8EABZn1X94is4BU19nZMVDUbbadWkq0KVRGdmJ7rraUiJ1w==,iv:suBMIrBIWagFv0/qJgJ8PGDmlLm87rLdhrStHESo6ok=,tag:bFoiyPnPg5/6Vz7vX7hw1A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1OGF3R1BnQ1F1ZjFZTTJ0
            K2FDK3Z2THRNUVYxMStiZGZjaFJHeVlFWUY0CmRXaGRHL2R1Z1F2V2ExM2N6ZXhy
            cW5qTXBkTDRadGlHaUdxRkFEOXJJbmsKLS0tIG8vbFUrUnU2NnJWUnNRZXdFc0dO
            SU5GOXJnRHRiQjVJQm5SV3dZMTdaQjgK+aI6Hf2czJbZQYz7zwlE+MIbusRQ+jeG
            7i9eDfY7cnrSEe8h+GIv9d6RFxTXzql9ySQkEMaZ+d/IoGpHslQaMg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h05qj66un22scwapuhyl76skls7ll235vlu27cjwkk5tpav6sqmsx3zp6a
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-07-24T07:25:04Z"
    mac: ENC[AES256_GCM,data:7Oxdp9ABKZuF3fdhD8oJoiRMgzxGN+Fg65lxUnOuF21Aya9AmgzcCAUsM/En8P1GUZXTVryERpBsKM1y2u1eYtJ0KrXL8lGITa3ybaTH9HhpJMv5ndP3frtoyfTKkgMwpeHNOiVSf0gluIWsFP6J2W9/QYr+BhaBmYeskmn1LeM=,iv:KVPqixQzPcVvPz5ButedEruZJcXGkykIjuijXIpsZxM=,tag:Vvi6YNFTH5UD1GkwnYvAxw==,type:str]
    version: 3.13.3
