apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: postgresql-secret
    namespace: jupyterhub
spec:
    secretTemplates:
        - name: postgresql-secret
          labels:
            app.kubernetes.io/name: postgresql
            app.kubernetes.io/component: database
          stringData:
            postgres-password: ENC[AES256_GCM,data:qoWD6T9Fm+coOugdRL0ym8HC3FRkw+a4CxKfF8NHte0=,iv:056FQY4NqKm8Z0tckEcz42+tbygeEYz81peEs0UnWLk=,tag:ACa6MDKsd0dCJJ86wz255w==,type:str]
            postgres-user: ENC[AES256_GCM,data:H4P4Hw==,iv:b++IglRSgbyWx5jnLG//Yg8bq7FreZ6Wm7r6soIFJUU=,tag:76rhRpryKoaya5xrWRy34g==,type:str]
            postgres-db: ENC[AES256_GCM,data:ks7nSg==,iv:r02DA8Hz9WLLazQ/S/VHtANc/gkZX3iVqBfSNf57W2c=,tag:7k/DjFSYdLPFM54kgvIzGA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3QWFxcDZCN0p3RytmV29M
            aHRQVGdFcnpNZ1IxcllPaTYxV3dFMjU2NEVVCkJ2UFhxYmhUelRsdDlCNmdzK0tz
            cHVFWlRET2ZXalVySWZVN05zWExOTkEKLS0tIC8zSEV1aWdlYWg1MnNMRS9oOFM0
            NlQwUVlrQ2lrRm14TnVrYytnVysvYVUKvyhK+j/GHJJWwVo55XMHafai2bISPXe5
            CXh2O2PFfPi/hHcprMFS8AV6/z74F+WY87boA/Lg8U5MIXX2Aq15VQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h05qj66un22scwapuhyl76skls7ll235vlu27cjwkk5tpav6sqmsx3zp6a
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-07-23T08:30:59Z"
    mac: ENC[AES256_GCM,data:htrrKPve/9k+yz7y4/3yKSxDdg4NVc/UDSMIzCR41uybAJpGi6iLyWelUrDQgG5xbAHx1ib+Z1TWs5a3ZTGDHXbUvQwTK8xTtS08S3Qs1wL4SwVM5z3pvLzFHCcgaPALlicQsSpitfUHnsjUcr1xirFAbg7uvS1QKHpzgcb9578=,iv:o7en5ynmvRCbgWx2Q8uVnkZIx/ohlJBwp0Ei/sU8OyM=,tag:Fxmajw0XdAtyqFNSw/py/Q==,type:str]
    version: 3.13.3
