apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: jupyterhub-proxy-token
    namespace: jupyterhub
spec:
    secretTemplates:
        - name: jupyterhub-proxy-token
          labels:
            app.kubernetes.io/name: jupyterhub
            app.kubernetes.io/component: proxy
          stringData:
            proxy-token: ENC[AES256_GCM,data:a7ES9CgPYXs1Xtj4AuFKXVvctX/agGGUa+EhYgAEepv6I3O7gSkWxf+qj3YjML/pMlBFIGaCdz4FMboiuM5r4w==,iv:bE3+IbreF6+mjEJTIFbG7yXj4eoiKlb0VJmeZ6IitIs=,tag:GE6RkMkJu+IYtcncJxuQig==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBWmI3Y0hKNk5mMTJIVkFx
            SHZIWkorWnl6QlB5UjNaQWNTU05hWTRXWEY4CnYrTGE2V3lxbXpFS2pMcXk4YW10
            NmxweTVXVnVvSTFnWVdtR0o2bURVeGMKLS0tIG1RR3BiNzdhQjZxZkhQSmdORy9s
            VlcrQ1JUSFU1a0dPYmFWTjVEUTBkdUEK9kHqP1Ts3Fi+XnbpKZP/SMB5mO8cf53h
            KDD8AqQy4l4eK2iSV5Dz82R+37SFsZnZ9C5/518Tj0Xx/y2PZGdvQw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h05qj66un22scwapuhyl76skls7ll235vlu27cjwkk5tpav6sqmsx3zp6a
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-07-23T08:52:16Z"
    mac: ENC[AES256_GCM,data:6n0v7+nNpZ42owODOGkN65rw/f6OjfJATiafpHbRtVDztFvGI+/T78YdeZSWMpeMrYbSByU/q3AHRr9lxwqe4oWmMLZaBA4bpt0t4BVe1uT4ygYrkaNN+tVXD2D5meKe+DD/nE6UTc33raZB2mTsR/aQXRVfe84Hiq10MoEDpIA=,iv:b6CgTz/riLoPuyGGT00KctWGF5QKOjpxt4OaNDxHwuU=,tag:42CtohpmwvTw7bEZBFHmGA==,type:str]
    version: 3.13.3
