apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jupyterhub-shared-storage
  namespace: jupyterhub
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn-overcommit
  resources:
    requests:
      storage: 500Gi
