#!/bin/bash

# Quick setup script for GPU cluster deployment
# This script runs all deployment steps in sequence

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

echo "==================================================="
echo "GPU Cluster Quick Setup"
echo "==================================================="
echo ""

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

function print_step() {
    echo -e "${GREEN}[STEP]${NC} $1"
}

function print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

function print_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

# Check prerequisites
print_step "Checking prerequisites..."

if ! command -v terraform &> /dev/null; then
    print_error "Terraform not found. Please install Terraform >= 1.5"
    exit 1
fi

if ! command -v ansible &> /dev/null; then
    print_error "Ansible not found. Please install Ansible >= 2.15"
    exit 1
fi

if ! command -v kubectl &> /dev/null; then
    print_warning "kubectl not found. Installing..."
    curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    chmod +x kubectl
    sudo mv kubectl /usr/local/bin/
fi

if ! command -v helm &> /dev/null; then
    print_warning "Helm not found. It will be installed by Ansible on control plane."
fi

echo ""
print_step "Prerequisites check complete!"
echo ""

# Step 1: Terraform
print_step "Step 1: Provisioning VMs with Terraform"
echo ""

cd "$PROJECT_ROOT/bootstrap-cluster/terraform"

if [ ! -f "proxmox.tfvars" ]; then
    print_error "proxmox.tfvars not found!"
    echo "Please create it from example.tfvars and configure your Proxmox settings."
    echo "  cp example.tfvars proxmox.tfvars"
    echo "  nano proxmox.tfvars"
    exit 1
fi

read -p "Run terraform apply? (y/n) " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    terraform init
    terraform plan -var-file=proxmox.tfvars
    terraform apply -var-file=proxmox.tfvars -auto-approve
    
    print_step "VMs provisioned successfully!"
else
    print_warning "Skipping Terraform. Make sure VMs are already provisioned."
fi

echo ""

# Step 2: Wait for VMs to be ready
print_step "Step 2: Waiting for VMs to boot..."
sleep 30

# Step 3: Ansible
print_step "Step 3: Installing K3s cluster with Ansible"
echo ""

cd "$PROJECT_ROOT/bootstrap-cluster/ansible"

if [ ! -f "inventory.ini" ]; then
    print_error "inventory.ini not found! Should have been generated by Terraform."
    exit 1
fi

read -p "Run Ansible playbooks? (y/n) " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    # Run full site playbook
    ansible-playbook -i inventory.ini playbooks/site.yml
    
    print_step "K3s cluster installed successfully!"
else
    print_warning "Skipping Ansible deployment."
fi

echo ""

# Step 4: Get kubeconfig
print_step "Step 4: Fetching kubeconfig"
echo ""

CONTROL_PLANE_IP=$(grep "k3s-cp1" inventory.ini | awk '{print $2}' | cut -d'=' -f2)
CONTROL_PLANE_USER=$(grep "ansible_user" inventory.ini | tail -1 | cut -d'=' -f2)

if [ -n "$CONTROL_PLANE_IP" ]; then
    scp ${CONTROL_PLANE_USER}@${CONTROL_PLANE_IP}:/etc/rancher/k3s/k3s.yaml "$PROJECT_ROOT/kubeconfig"
    sed -i "s/127.0.0.1/${CONTROL_PLANE_IP}/g" "$PROJECT_ROOT/kubeconfig"
    
    export KUBECONFIG="$PROJECT_ROOT/kubeconfig"
    
    print_step "Kubeconfig saved to $PROJECT_ROOT/kubeconfig"
    echo "Export it with: export KUBECONFIG=$PROJECT_ROOT/kubeconfig"
else
    print_error "Could not determine control plane IP"
fi

echo ""

# Step 5: Verify cluster
print_step "Step 5: Verifying cluster"
echo ""

if [ -f "$PROJECT_ROOT/kubeconfig" ]; then
    export KUBECONFIG="$PROJECT_ROOT/kubeconfig"
    
    echo "Nodes:"
    kubectl get nodes -o wide
    
    echo ""
    echo "StorageClasses:"
    kubectl get sc
    
    echo ""
    echo "GPU Operator Pods:"
    kubectl get pods -n gpu-operator
    
    echo ""
    echo "GPU Resources:"
    kubectl get nodes -o json | jq -r '.items[] | select(.status.capacity."nvidia.com/gpu" != null) | "\(.metadata.name): \(.status.capacity."nvidia.com/gpu") GPUs"' || true
fi

echo ""
echo "==================================================="
echo "Cluster deployment complete!"
echo "==================================================="
echo ""
echo "Next steps:"
echo "1. Install Rancher:"
echo "   kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.13.0/cert-manager.yaml"
echo "   helm install rancher rancher-stable/rancher --namespace cattle-system --create-namespace --set hostname=rancher.cluster.local"
echo ""
echo "2. Configure Fleet GitOps (see cluster-maintenance/README.md)"
echo ""
echo "3. Deploy JupyterHub (see cluster-maintenance/clusters/homelab/jupyterhub/README.md)"
echo ""
echo "Kubeconfig: export KUBECONFIG=$PROJECT_ROOT/kubeconfig"
echo ""
