apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: openwebui-oidc
    namespace: openwebui
spec:
    secretTemplates:
        - name: openwebui-oidc
          stringData:
            OAUTH_CLIENT_ID: ENC[AES256_GCM,data:yg0M9XFkX/Gu0pzPDiSK42boZbBpjMlqFFyGOvL30Dqcmgzj5nj+xA==,iv:Ug+mmD+qPICeLgdHrS2EBKqAQ6+y75/6knF/KF2xZ2o=,tag:peLLV4h/rW3483UnlwV4nw==,type:str]
            OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:jd1rLbelLNU0tI51BG1aw67JxX/UE3IqybRrnA4/VqHnaF6ZZX8UPFeOpbkG/O/xe3xi4rCP7Yo1/n1q4AffWSqA6q+vkWhvdbZBj5OoGcZgKiNo7CE2bV4GIhKlIP/XCF0SH1xB7QcllpXD/b/yR2fanSD6ftu6X9F+Kk2c530=,iv:wC3HT748SohTZd0p0qp2KoQ4fB7TZP+4HNBs72aaNSg=,tag:L4JKf3YABzYyyyOPTCaDvQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTNlFuQy8rbG00eEFyellR
            OTRpbkdxWFRZN2IwQjR0MnpUZnA3NmhsdmhBClVlYU9pc2pucmtCYlo3S1QvUXNE
            RlFxek1lSmxqbVdyaWpKeXliN0poZTgKLS0tIGtMRERFd3NvZXBTU0NEeHE4UFZE
            VTBGRjNKeHRnS05sZkZnTkREL2pJeWcKkX0SRtD/ehdYuHScUjOnUbabqpHQiD1D
            BDwx/1tLEJhDXVn16hPzumt1kJQyOjZAmA5BsGrGokanWNs4pwiZvA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h05qj66un22scwapuhyl76skls7ll235vlu27cjwkk5tpav6sqmsx3zp6a
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-07-23T09:27:38Z"
    mac: ENC[AES256_GCM,data:C9rVH7wMnMIq46jzZh0KoxvPcvUFBfDA4Mki4Z7GVmk6yUZdX4B38Gc+sAVbIrQzrELQZ9uOyt6Oip8nVkfOU9WVmzFk/zjqrb7J2K31DhpDo7WHxZbnOllo6kOwnnkZgNVj7cx8hWXjjwUdyv1bquSUt/gaJrZnJNh+uxvZ3SY=,iv:dRGOGu8gz3M0qnf639m9whk9ruw0wVp2j8cPZRupwRk=,tag:yX1mqNi9BmcZMgSpDbEcOg==,type:str]
    version: 3.13.3
