apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: openwebui-oidc
    namespace: openwebui
spec:
    secretTemplates:
        - name: openwebui-oidc
          stringData:
            OAUTH_CLIENT_ID: ENC[AES256_GCM,data:hCbsVR7uLeDAI/RvcBafnROdnP2rbtEgHApO0T4YVgbGezI5I2/hzg==,iv:WelaCW6w5CytaK/NXkQ9mxVzgeLf4cBY+fYjpBg+nfQ=,tag:F346nsliZqT3/mAkFNgUqw==,type:str]
            OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:fGnnaXw2RkefipICm0Juig4/O7hLzOzDuXbMvBnQ69CqpNh1UfQvoPjGAvnkuIHHHmsVGOQ2gjDuCPRkQHW5EI1SjpNh8QFu3N5MBXOF+1vw1UiczTlrDZMOvBcoFrraP3SC9AzfOsSz5ooYJi/p6ymb0QK0GiPKV35zxbviJA==,iv:2MviKzCMta0K4KyRpUOLAqKxuBa+ju6sgiLIu4er1js=,tag:ANEHbKxIBnITJ1LRU43CcQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVUXJ0RzUybVRJZU4wdnNO
            T2kwV09IdUFlNkNvU3Iwb3NRMGdtNFNTM3lJCm1GUzg4SGMzRkw2Wlp5RXpvNTAv
            ajZrTFduQVZNdXM1ZzF0ZFE2U2tXMXcKLS0tIDBwenF5VDU1T0ExcDdPYmhQU1Ey
            SUZHWHJtZ1IvN3A0ZEVobnA1MnFYd00KPnxApRZ4g6S6DIUbMNOnzmNKEUy5j+LG
            iUK9DxHFgpDBNQyG3EYE7xiMZwb75rSmjhSHpGhAucdZgo0SkrTlNg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h05qj66un22scwapuhyl76skls7ll235vlu27cjwkk5tpav6sqmsx3zp6a
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-07-23T09:41:45Z"
    mac: ENC[AES256_GCM,data:+BK6CLCw6RtZMyGgYIE6CG5qDRifawZIxqrP6Q15IgcAGZAxKh4+UeB10tZMsSpnqlwIyxipCTBPH1g32k586JE1dbZaxkTf6x/2La6QxjD34dBdlqi+9vVOJyX9NxYAZ8Hs4rX3/HHPtMrTSABlllw204UjNTVtXkSzBvnaQmU=,iv:Vdqt4loYTey0E0CCvn4p3FWczyhttTB2kYRMDcQFrr8=,tag:b21q3E7NrCpNZzNMst0olA==,type:str]
    version: 3.13.3
