apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: argo-artifact-image-pull
    namespace: cps-argo
spec:
    secretTemplates:
        - name: argo-artifact-image-pull
          type: kubernetes.io/dockerconfigjson
          stringData:
            .dockerconfigjson: ENC[AES256_GCM,data:7GWOc+aehYa2T8XM38Wkw6XUaCn70NEql5m8Avg8b0dnkQA9qbn8OpqeI7Nwy0vHK9/+9BjUo7g4Cp+gfRfklc8vKDYhwBHd4ohtlC6DwS4iCFmGwcqgC1W/v7Q9ahGj12yR2fHAVm8h,iv:XIJsMBZcLASrT5uFdU4uEg1180KhD1mIFgFJhmfXSJ8=,tag:wQ4VZv2G4j4CSaq/g1ulGA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFZzdyVDVYYnc3WTh5WFFW
            T0gwWkpzSUNSQzZPZmJzN0ZOeUJRN0VEY1hVCnA2dWRRUWhCOTVSTy9EclY4UHhJ
            amlHRVo4UjJCVjIyb3JWMlpUbXoraXcKLS0tIFpTbmc0N2d4eEpydGRPckFzc2tG
            TGpkQ2hjMWdidXpSVHhUanRlc2xpODQK60CVx8/Zk14XUSEIKq+3T115BlZ+5bEM
            NF1GfoC3yHmK2UxnfG+8vUG8hyHoAfRDzERSoZN2x8zMX/d3nJx5ow==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h05qj66un22scwapuhyl76skls7ll235vlu27cjwkk5tpav6sqmsx3zp6a
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-10-07T11:33:26Z"
    mac: ENC[AES256_GCM,data:Q2SfhIeXr92tED/rXKVAuuUwcJsdf7YYg5uWMwpdp08bQRYmHTwolpX8gDG6bBWobfQGC0agbeI2qDfQoaj6SF4148mw0aVaMT6oejg0WlXjm1VxzpuwJutEuiQGHdromGCRcOJzDvbGFMGy1KbJL3iYHgIDBXAd/0J96/bhHEI=,iv:m6OsVEL7yYykJ9vJDYnWK3C0DdofZxUnpuE9+HkFOk0=,tag:jPGdcs/eD3khh6I8ucllWQ==,type:str]
    version: 3.13.3
