apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: slurm-shared
  namespace: slurm
spec:
  accessModes: [ReadWriteMany]
  storageClassName: longhorn
  resources:
    requests:
      storage: 500Gi
