apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: dex-cit-connector
    namespace: dex
spec:
    secretTemplates:
        - name: dex-cit-connector
          stringData:
            clientSecret: ENC[AES256_GCM,data:fwqBC31GCQ5DTkJPDMiDerQ9gYUfKvIrMTIwDQXiVa2tovDrR9oKKOE2ZiyM9RXumadzG7gewHLQCIwHYr5H2kTh3ju7oO1hC5/TDTiJAXTJc/eHFzRLWqB8sMSmasRegAwhMX0ce3evWFKccKv3r1G4oYLDmG34fOs7DcH/CTg=,iv:tYsvxQOD72Jle80IWoFF7dhKA/4iD5NLBYtd3EFmZ/I=,tag:wE6RKnFCg30pWXQsRo4qLQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSMjJXZWhjOVpvL2xOeGxW
            SWIxOGdZVEgzWGlFT3dGa2xKWkJGS2J1eW5rClpMTk43Q2ZrV0NUOEF4SUlBakhs
            RkVkdkZyOHRLQmdld29ZaEhEbi9JNE0KLS0tIHdLWFc4Qi9uZlBiRFI5WUVGWUQv
            QUQ3Ym4rSko2VTJPQ1UydXpNV1oxdGcKSlWAgYZ18IQTQifAqW8aOpgyQsOk31yp
            0FX0NRMSZw6b2ytB1CK1/n97/6S8yS2EpIuBblDT2zfQ0DyMwDFk9g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h05qj66un22scwapuhyl76skls7ll235vlu27cjwkk5tpav6sqmsx3zp6a
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-07-23T13:00:17Z"
    mac: ENC[AES256_GCM,data:kNfBEKtp/45TrsJMmtlnim9vyaXeJq/cTIMnmIovNkVn6CwxdzlBcXWCNhmgEDgn2aROAGUKbyy27lLH5qSfRmkOKeX2qkeQH+/QArmQVfUWDBc2ZZqcQkhp5hTlsFRHD1nbpTua1pzrkdQn6epTbRzDTFfExRapcLYyZJYsvFM=,iv:sw1vLA+1nTxeDLHEAaZ9tUoVQZNjB21ESwyEHmE8GQw=,tag:aEkaFBIcwZKdhmzQ8aEZlA==,type:str]
    version: 3.13.3
