apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: dex-cit-jhub-client
    namespace: dex
spec:
    secretTemplates:
        - name: dex-cit-jhub-client
          stringData:
            clientSecret: ENC[AES256_GCM,data:5gvxQIc8r9SxBQc/FiDJ4Mo+iqU5DtFuYQ0ousDyC1w6HbwuzdPtvy6JQAmY8hA/nZPYHOB0Gqc3PYvcgA6o9w==,iv:C4iBNSznlYIDINZNKtNmU1Mo9DRONyG7jgZmS6JiWbM=,tag:7jAXs+i5bFGf07fZwgkERQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxZzdrbGZMVkswYjA3U3Ru
            VDEvRDVWYWtDSkpGd2Q1V2wxQy9lS29vVGpFCkxtVmsyUlphTlFsUHhKT0VRbnBB
            a3EzVjNVQzNUMUpWSWJQVWkzVTQxK1kKLS0tIG1JUGp5dTZoWU9BMjJ1ekZUL0Yz
            S0E4ZHlTY0x0aVo0NDJxaUFodk9FSUUKdC80AzO6mh822T0b8FofoziOAc34NJ/T
            9nBatW9MR2eAp8nVVOKZeIMDO9u7z/3GSl4/F57tNuy5uoVSZAbj3Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h05qj66un22scwapuhyl76skls7ll235vlu27cjwkk5tpav6sqmsx3zp6a
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-07-24T08:34:12Z"
    mac: ENC[AES256_GCM,data:4t/7fK+B9H1ajlR54LjKUyOIzfAN2eQou2//o7FZKV4+AhFjE1OG8o9JZf33FZuP3Yv8unSigF+/sVPvLpz2K9BKTk6QqPRyUfL5/Zyeali26UAst8B1xRXssszqpNTsRPOQ+pdmL9uZbym2wLyE7JRnFUbWhumBBW3a3n5TW+g=,iv:TfJht0x1/81rON61NvtxvUmx8S2ndCCmLtwYscmi9do=,tag:VrgPpEHyZXUw/VaHuRdlvA==,type:str]
    version: 3.13.3
