apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: dex-cps-connector
    namespace: dex
spec:
    secretTemplates:
        - name: dex-cps-connector
          stringData:
            clientSecret: ENC[AES256_GCM,data:y0QhSjHwIKXehnAw7ObyOd5cPZkazEHke1QVaSrfupZsFDsx/pDL4a/jJG3eIa/DoLm/0umX9nTv1aD2BlhTYkoHQ2iaRj7WuyfMTM7w5+DYg4xRyuLjF6LnSy+eIZ8IDwWaUlV0Nrh0HRKMP1UgVmpRdrRI2VVGm6WmpOSQs5A=,iv:eUuCnI+de8jW4z9I0nAUk0Z60zqQt5nELMIBHHCb3ok=,tag:u27ayz50vXAj1yi1jgBbQQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYU0RqL2MrMnMvNWxTQk9C
            ZVNqRm5ESWpqUU0wajI5akNpQUFJTWJQdkQwClBFdUlPWWJvODh2a0ozR3h4ZUtH
            aTZmSlRWVVJ2T3NkcEhOR0VlUVo2ZWsKLS0tIHJ1Nm5hRVJPMlowTzNob2tFWE9x
            TnlMa0FUcEtkVmVnbHZJR0JvZWZtN0kK369JuF9pCrrylupVcqLPdZknjGfe45wK
            XoLpxQUYdnBjqmX1GWR7PwwwV9aeeVi1i79iKOaHLzkbFM+g/lb5dQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h05qj66un22scwapuhyl76skls7ll235vlu27cjwkk5tpav6sqmsx3zp6a
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-07-23T13:00:17Z"
    mac: ENC[AES256_GCM,data:yycDcFZK/Nzd9wLosPMQIcBN6w5PKAYKYrmbRm9tAMVj05ppKzYiUvmLWl3MkuFZpLIEquEdLFOgsQtYoMNP8dOGYfRCxWmOMnePHhGQP9N+U0s1yxF3O4lkErFi1W7Dpipz2sfmUHErXpL+8v3VhN7ztwH1jT5BISs5uILkC64=,iv:A8EN4XthYsrsBH6Iqj7CiEOFqaDn5sdB71wnlJ8a5dw=,tag:B0jwyeus3q/ygviJ9cQyuw==,type:str]
    version: 3.13.3
