apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: dex-jhub-client
    namespace: dex
spec:
    secretTemplates:
        - name: dex-jhub-client
          stringData:
            clientSecret: ENC[AES256_GCM,data:4jAIqvitBPyKKpGK5/8Kb3mkitbbh5kTOwbBEGFjQZoaUJpE+p3KaL8vC8f+ADKy9EgkCLqliyRtXtPApqyOIw==,iv:sI++7SfHvwCZ+DpZ1hn7BmBELyuNwevU4nfAMI5JnNM=,tag:i4LR8dXrhrs9KEce7cx+dg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtUS9KUzhESG9qNUZmc1Ni
            ZjRSeWV6UjVQRlhWYkZWenlPblpZZ0F6eEI4CmhMN1dLckRuRGtLK1Y2OWZwVkxJ
            cVR5amhJMkFNaVFuZ0loU0lvYllmeHMKLS0tIDdIY0V6VXg4UXdXRjJvR1prRkJV
            N0tRN1lYMGFRWXd6MEc1QkU5YmdiUjQKpdZ/voJotTgnwFmhlgt/4/6gsGhqvyNb
            WbQMvtUAhHXwgJ8IEPvG4eyZeD9NC2QWYrkl9uMyn0YMJEu2Q9riPg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h05qj66un22scwapuhyl76skls7ll235vlu27cjwkk5tpav6sqmsx3zp6a
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-07-24T07:23:02Z"
    mac: ENC[AES256_GCM,data:xkvvZtA2akv49xsIID6gdg5PYuLqd4V21WL1aLZUFN/+pIaqjqH2vwCYKnC/GMqp1GWgnLIa1hJs+e3WB59HxoopltgaoHpzYabPDDQYW9mhDky5ENvWWDMnP4SgtUe4iXz7GSR0f/MGMlNNwF1sEYMCoBdcw/IzytfIxOQ3cbQ=,iv:/yMUGucI+msXGAv6lwHvnMnZVPi0+fGnRDhDq07R6rs=,tag:n9KnMOwpyTpb8syyiKEWrg==,type:str]
    version: 3.13.3
