apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cps-connector-sopssecret.yaml
  - cit-connector-sopssecret.yaml
  - rancher-client-sopssecret.yaml
  - rancher-secret-sync-job.yaml
  - jhub-client-sopssecret.yaml
  - jhub-secret-sync-job.yaml
