apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: dex-rancher-client
    namespace: dex
spec:
    secretTemplates:
        - name: dex-rancher-client
          stringData:
            clientSecret: ENC[AES256_GCM,data:anRkxcnmBVr7RyXi8iaxBnL6ucQDjgKh6r3J+5Pxz5M/vCZzFVzowFXTTkTq4dIPxgky/350w5fNdRxbQtRA+A==,iv:4zffkeXy1IBLJXMfiKgT+J90ACAlfIHKed32zQ36zoU=,tag:zFbQPfdgtLJ25v0bk0L3YA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsZ3Z2MHRFODB4TEhIYWU1
            dytuTnJ3T01aU09XVzZnc1lqMGYwYUtlZ0F3CkNNWXhIOWdkVmRIbHRIbStnZURQ
            bVdzWExUa2ozL0xuUXFpdDNlc3NQZnMKLS0tIGtTYWMrZXBKVnRVK3pGd1o3MDgz
            OUIvZ1BPSTJjcmM3SE5Hc212dzBZakUKF28kBpgHE4UW5Xk5ZgOVNmogLBmH8ngn
            TEci5LGoJT44X5wgNuYNPO6wYSpqx3ay3ialMolCZHDBZ5JjVmca2A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h05qj66un22scwapuhyl76skls7ll235vlu27cjwkk5tpav6sqmsx3zp6a
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-07-23T13:00:17Z"
    mac: ENC[AES256_GCM,data:xacXYTtShkkDBfe70IT/HPjfgMkNYdG+JyC1/T6TbnHdL6i/27VxE1wbnC9FiS9FEdDAK19DdxaV62DfK0LMiDHCu/vqxWU+Vf+bVT4lrfvglKtWEKp8suHOY+iI9KvM0li1sCva2y+O97FYa5GQys/Ikqv/h7z8gGJrX4OYpeE=,iv:o3A0NapYZV0dDkQ1sY5dCYfjjHO7QbpSQS3S2LgfU+o=,tag:KwVkfPGgKDAbY7J55OFepA==,type:str]
    version: 3.13.3
