apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: rancher-oidc-secret
    namespace: cattle-system
spec:
    secretTemplates:
        - name: rancher-oidc-secret
          stringData:
            clientSecret: ENC[AES256_GCM,data:fCFXoDTt+wEB2aTlX8O96p0jnKW8SvU5vc3YbB3ctIQylawogvkR/ieafHpTe13X67Rf0MOCHm1QTyXu1thp620Y6Ceq5un+d5ivJVlwrAKKvQO7wbG12Q+ofO4zXx1D7b08urSwPCvH4wSSEiPkt0p5Q4GDrk/2TV2QKAI=,iv:+uDH+XbODyUgwo6M3SR80JLpx5r+ODxoyp+28t3IPkg=,tag:Q9ZFp/S7nEH5383M4wY5Aw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrMVZTT3JIaHlkMUxxbnhw
            WHc4N09UVzlXZFZWTzRSd2xkMVNndGtBbjI4ClBoa0xwUUlMM3BpaWl5UVVkNE9O
            bDBVbTU4cUJZcy8wa0U1d25KTWVYL0UKLS0tIG4yWkJkVWxNN1kxdll6eXVibFJK
            NGVzWnA2WGRPWXVwSFUvWnVJQVZ2ODQKxlqnYd6CsuFdTOMAjbMU30G1GErGfY8r
            2Em9BVmwHwkch4MJvzKc4atfardrPBXklqtACYQq7XWUx/IWbObwXQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h05qj66un22scwapuhyl76skls7ll235vlu27cjwkk5tpav6sqmsx3zp6a
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-07-23T09:57:36Z"
    mac: ENC[AES256_GCM,data:2r7039kV1BnU8TlRrp9aS9yJirPbi0vNguZkbG/80s8EqyClbJpyGnN+YMmp+5NZfx+lrXm/akjaIfOTsk5Us7faDJlg9V02BWtH1VLdGJS7hAIoG6BCWIvOkMLs7e7zXiFis+Qaa6rKzqT8hjJJej0c+Mn4nFDzRPN/Su9pA1U=,iv:mT8c2lhv+uF47jac+fJ6mRDhRTDbE48OqDJgtmCRxQw=,tag:fFHDGiNtYo5jZ5/RYlgb2Q==,type:str]
    version: 3.13.3
