apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: rancher-oidc-secret
    namespace: cattle-system
spec:
    secretTemplates:
        - name: rancher-oidc-secret
          stringData:
            clientSecret: ENC[AES256_GCM,data:XdN4/BzpAy9yDmksY0a9CYXcMwVXkqXP3x1HOMx6TSxNrTLAqejc3Ble5GwpOYB7HPB7DooKfau3aFMWHz7eag==,iv:224fV9YrbEt0PlzZTHQ2/XwaA5S8Rl3xITBh1H6/72M=,tag:NA+kFnmJEYvgCB2904PEMg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDNVV2cHdOTVVhVWxkSHdU
            TmphTVF5TVppZFlKNDJ1cnVBOGMzdEQydkRJCjc2eVI1YW9hYzF5ZDZ3c3hKd2tm
            RnVnRmpVSU9GQ2lVbTBDMzI3eXhkUW8KLS0tIGxqZFF1ejVVY3pOM2dNNlFCT0NS
            eUdDS1dUb3VOejUxdjlJZ0dBd3FldzAKbJvXmv0C469oInVg1oRtOABBUQdtZFh/
            sCMYwVX/7d/EdTkYzAgODX6pWT+gHaYj8HSpg+LC9i2LF4iWoa+xLw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h05qj66un22scwapuhyl76skls7ll235vlu27cjwkk5tpav6sqmsx3zp6a
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-07-23T14:06:37Z"
    mac: ENC[AES256_GCM,data:84QQ1idxAcNWvIJ581jwCXds7p2Qx3MIyfv7phNJ3i1/IVCzJsZa9xCGuznAa8CKPpI3HoM5oATAPfoGjCm1u3DS89l78u4VGgiOafcZrBrJMJJxq60obfjYoZ3mmkEn63BI4wHoQC87Cm2XIyeTotAXnunQLK2mp4h+Uex0RkU=,iv:ur7q69NC+FheaW1qrCwNzcHqKkNMnc1FKli4dsKDi+E=,tag:S53SKHCjqsdg3XgGUqyNJA==,type:str]
    version: 3.13.3
