apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: rancher-oidc-secret
    namespace: cattle-system
spec:
    secretTemplates:
        - name: rancher-oidc-secret
          stringData:
            clientSecret: ENC[AES256_GCM,data:46nR3Iuw7cvtxw62zagrK3L1ZAISsi25U9bLLU6muMboNWyBCjiQCi1k9kBkDqqW5ZYgbpAhaTMFtJ5qdRZIqAbYLbE2p+g6r3hd6od74kNo1gB/em1VOqZU9C5kBzppA5cB6GGCvHOIn9vNsCyFVF3JJAuxJ8ZxpN8tRCsok1w=,iv:3tlfjLZHwusU9bA2isQbuz0icI/XTs12D1jGYDalPgw=,tag:y3N4odMSNx/58+jqDoZDxw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkdDBZVU53d2hXUGJTYnNn
            UmRXT1FvRkRsWm04bUxzNFA3Z2wzSmNwb0RBCmxUM05GY2JEZlF1YkRSd2VaaTBT
            T21FaVZqK2pCWm5rQVpKNnd1RXpGdlkKLS0tIFVTRVZCc1dQSjdBdGlsUGtZQVVz
            SXBDN2JieGQvdmpXak0rWnVRUm1iUkkKonxX5FY1rzYwDJePl4ZcVqLYqotzQLf3
            IU4SryFqQYb6AV1+VX33AuJlY+n4zZTIVtCIv4mmtBRcgOIaiBtWBw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h05qj66un22scwapuhyl76skls7ll235vlu27cjwkk5tpav6sqmsx3zp6a
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-07-23T08:59:46Z"
    mac: ENC[AES256_GCM,data:0dvRqJSz3FN5QLSBNFbtc3u66M5d4qltsmc+uw4RcqWp43fc1tTF9d/l1t4ewoL8lrMS9BRLyUudD/KZjCghDflkvUMzYz0Xn9PEGuLPXGkYnOqjnnfTo/KpXurVdeqB3YQOFyiJDSjD/k9v23uR5PkDI/bhIEbt0Liu4FG1dTE=,iv:SLR0gwUKK0/KmEFBmreRScBQXvcoLSLlLrRP/2D3DOM=,tag:7SCBa8JA7/Oxda6Or0dTYg==,type:str]
    version: 3.13.3
