apiVersion: management.cattle.io/v3
kind: AuthConfig
metadata:
  name: oidc
enabled: true
accessMode: {{ rancher_oidc.access_mode }}
clientId: {{ rancher_oidc.client_id }}
clientSecret: {{ rancher_oidc.client_secret }}
issuer: {{ rancher_oidc.issuer }}
authEndpoint: {{ rancher_oidc.auth_url }}
tokenEndpoint: {{ rancher_oidc.token_url }}
userInfoEndpoint: {{ rancher_oidc.userinfo_url }}
logoutEndpoint: {{ rancher_oidc.logout_url }}
jwksEndpoint: {{ rancher_oidc.jwks_url }}
scopes: 0
displayNameField: "name"
userNameField: "preferred_username"
userIDField: "sub"
groupsField: "groups"
rancherURL: "https://{{ rancher_hostname }}"