apiVersion: management.cattle.io/v3
kind: AuthConfig
metadata:
  name: adfs

accessMode: unrestricted
enabled: true

# Rancher uses the "ADFS" SAML provider type for generic SAML (incl. authentik)
type: adfs
_type: adfsConfig

# Required SAML fields (Rancher SamlConfig)
rancherApiHost: https://rancher.dshl.unileoben.ac.at

# Claims/attributes (per authentik Rancher guide)
displayNameField: "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name"
userNameField: "http://schemas.goauthentik.io/2021/02/saml/username"
uidField: "rancherUidUsername"
groupsField: "http://schemas.xmlsoap.org/claims/Group"

# IdP metadata (from authentik SAML Provider)
idpMetadataContent: |-
  <md:EntityDescriptor xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" xmlns:ds="http://www.w3.org/2000/09/xmldsig#" xmlns:md="urn:oasis:names:tc:SAML:2.0:metadata" xmlns:xenc="http://www.w3.org/2001/04/xmlenc#" ID="_fd79ebdc6d5d112c381d4a5292ade2d126f81663221a35345e0215a57273d8aa" entityID="authentik"><ds:Signature>
  <ds:SignedInfo>
  <ds:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
  <ds:SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256"/>
  <ds:Reference URI="#_fd79ebdc6d5d112c381d4a5292ade2d126f81663221a35345e0215a57273d8aa">
  <ds:Transforms>
  <ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
  <ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
  </ds:Transforms>
  <ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/>
  <ds:DigestValue>fr+p1SSiDYLOlQGp5EHrBD6x0Hk+dpKZujbFOj4UDH8=</ds:DigestValue>
  </ds:Reference>
  </ds:SignedInfo>
  <ds:SignatureValue>HSx/IIiGRSE8fR3F5j7ywxgfMl0cJ94QXAohQ97U47Pq+RGZMcKPO9Bcni/xaIdA
  f8zIa+xOYRyGYzcBTf6xbtkr2TYr3fIf5tuzMQXgTvVIDr0gRybnI9ODHucP7zHG
  mR73qL5rq4wE8UMf0x1KQRKHh/Am7ccmKNITLE/GMNqeUOximbP4QwTfdQi7J2pC
  eynFekpD1OVYU0eAOV6ldXzzci65g2PgCDzu40H6gSUAKjKSZInL5xFQRLRAqSiB
  16E08MhAGMAl4byj2ZJWuLHuLYcYxg/OeL8B/7hBi5xu5PtJBNXfLTkd5/IpTKzL
  PdjM8CpPiBewqgnPiHAQng6gvMxUKD6NONvdIaPe6VDCaqVoiUMz6K60gEk/CzFO
  R/ZAfMz1541vKCJQy/ao+wmkBwCye9omgLHD3MU0o0OxePmGPU7RyO6U75A3kHbU
  5ERY4Ifnk6UWlBysFG1mrhPKToNv61fWyFDMrztFkV3MCi+P1bdMmluwa4utIZa4
  62ebSpDWcopw3XWQmaxBN/Kzd0fX619r9iWFrfNeMPIQeUA1/qmO9XH70SDB8hTs
  tkYK/kS83jVrEeiZnrFicHtMaVHOYPYN4gEWPz8uFEpeQlBRgzyrCuqGOJlTaisE
  34c6aYwlmQ2Ktj86gQZ5R0vnZKwwJO1CO0UwDjw2zcg=</ds:SignatureValue>
  <ds:KeyInfo>
  <ds:X509Data>
  <ds:X509Certificate>MIIFUzCCAzugAwIBAgIRAPqZVIiLh0Lnrqa01fAdO7gwDQYJKoZIhvcNAQELBQAw
  HTEbMBkGA1UEAwwSYXV0aGVudGlrIDIwMjQuMi4yMB4XDTI0MDQyODA3MDMyNloX
  DTI1MDQyOTA3MDMyNlowVjEqMCgGA1UEAwwhYXV0aGVudGlrIFNlbGYtc2lnbmVk
  IENlcnRpZmljYXRlMRIwEAYDVQQKDAlhdXRoZW50aWsxFDASBgNVBAsMC1NlbGYt
  c2lnbmVkMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAz6hnquKC3xGc
  PMFxuX7vy+zwh7Nd0X25bnPSjKAP0vfC15YE+mfOzHD4YOHChhcupTQT/IjHpQtp
  4yqtSwUtaB9rgRgKPx82yy6VqDrsEomX0Acu9c37e3PIY4Zee1S7UDumbzJ7FNC2
  xHA7dCTnKPxyZSBNc/kcwv5T4V8VQdHs9JzJRroLAvxrAVpgK6UYlicf6bL186wU
  Y+6JQG96LJbi49AP1A0KH9hJGY6cdqbc/ocy0O7MVD4qAmbHhQTjqjThmI+y5CEY
  ctSqB3gdrxhGgkSwJ4rUxHobEaGwZ+sncchqBr1XxabGjllJJpZsLzrZDDb38hE+
  157QFQ2VE9wcr6s7tCDG0vTuiCGUP1VvKAQjVf+p8oc+FZ5GJ2q0gk+V4lNjBxzD
  Rxozt7ly258rnYcch/qkljZCikUEiybnh7Adccr92iYg0CHM21DrPNAR0z6eRDVH
  0mr0M0KbzffYBH76Iwavpwr15Gxfj2RJJa6+GQwPaceqG786G7UMqHO/i1cZ2KVz
  B5HLNPw62P4SRqhZR70xY+XRwHrDekSS2oy/X+n3wBvpgSWqzmRkQdV+LeVIypQ5
  2D3ZploZzbV6c/VdolAf1GNAtEEPc8rgaOq/P5jGx1Cz92+0kFcbBLr6XZ6CEuh8
  Uz+cof2u9AMsCwXA+uymdDR7O0jIhccCAwEAAaNVMFMwUQYDVR0RAQH/BEcwRYJD
  cHpobzlJRDVIRUZMaU9kejR6NDdNdWlqQnpRUGx5VzZLbVV4dVNTaS5zZWxmLXNp
  Z25lZC5nb2F1dGhlbnRpay5pbzANBgkqhkiG9w0BAQsFAAOCAgEAFf5qBwPYX1mz
  D4QkXjyi8yxoGONtlxseziDFAu/OVrLi34fQ6P9Ftuor95f1bkwLFgfidKZ7AMg2
  r2wml7ug6nhkETNss22qIG8amQuYQNWOAtG8Va2B0oHO/tlr8j5KePzZ2PabkJlP
  fyQ3YZTgjm6ExDKC5ARj8YETBJPA+Fywo/CVnXmUP8vCRm5eDSpvZcdAbcZ4eyDs
  gy17Pr5upFf4ctfPm9XR5/Qm7R/6XR927M2GttWKa3uqpcRiLlNpPVT8CVZkrHuh
  K9L+OKxOU0hv7pfkfYDPdl9tdj9M6Au0XmevtLEnQNay7XlJWw89otiySsH4vFAN
  286aa40qYwjC23/AVICEuq+UqZAh3d4+cXBjUWb1sWOAtpIeATE4rlgFDkZVYkcu
  6xRVlg6Z3mKmNFeGb434jsC6GbgikWSsRkSWqT6gdvLb+ieQlFBxlD1IrKHUYHqx
  rprsSXPlMCTA13KvrKb53/lAYBJ6n+NKK21Iejaek+k7tgSB4wFOUP3rVSUD4v0Y
  buZKlJG1scJfXmtSlwBSp8u2h0Yin83W5vmKCTx5AT+XpDZhzHSim3ABwot5Vgqy
  lQ6d0iCrMkxZcT6HSNo4u7mZQHANF48QhG4iN5FVZNnkNxZOacrTTQiFYwZp5Ub7
  Og2/maMEUELxRGEehs569jsL3tCY+PE=
  </ds:X509Certificate>
  </ds:X509Data>
  </ds:KeyInfo>
  </ds:Signature><md:IDPSSODescriptor protocolSupportEnumeration="urn:oasis:names:tc:SAML:2.0:protocol"><md:KeyDescriptor use="signing"><ds:KeyInfo><ds:X509Data><ds:X509Certificate>MIIFUzCCAzugAwIBAgIRAPqZVIiLh0Lnrqa01fAdO7gwDQYJKoZIhvcNAQELBQAwHTEbMBkGA1UEAwwSYXV0aGVudGlrIDIwMjQuMi4yMB4XDTI0MDQyODA3MDMyNloXDTI1MDQyOTA3MDMyNlowVjEqMCgGA1UEAwwhYXV0aGVudGlrIFNlbGYtc2lnbmVkIENlcnRpZmljYXRlMRIwEAYDVQQKDAlhdXRoZW50aWsxFDASBgNVBAsMC1NlbGYtc2lnbmVkMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAz6hnquKC3xGcPMFxuX7vy+zwh7Nd0X25bnPSjKAP0vfC15YE+mfOzHD4YOHChhcupTQT/IjHpQtp4yqtSwUtaB9rgRgKPx82yy6VqDrsEomX0Acu9c37e3PIY4Zee1S7UDumbzJ7FNC2xHA7dCTnKPxyZSBNc/kcwv5T4V8VQdHs9JzJRroLAvxrAVpgK6UYlicf6bL186wUY+6JQG96LJbi49AP1A0KH9hJGY6cdqbc/ocy0O7MVD4qAmbHhQTjqjThmI+y5CEYctSqB3gdrxhGgkSwJ4rUxHobEaGwZ+sncchqBr1XxabGjllJJpZsLzrZDDb38hE+157QFQ2VE9wcr6s7tCDG0vTuiCGUP1VvKAQjVf+p8oc+FZ5GJ2q0gk+V4lNjBxzDRxozt7ly258rnYcch/qkljZCikUEiybnh7Adccr92iYg0CHM21DrPNAR0z6eRDVH0mr0M0KbzffYBH76Iwavpwr15Gxfj2RJJa6+GQwPaceqG786G7UMqHO/i1cZ2KVzB5HLNPw62P4SRqhZR70xY+XRwHrDekSS2oy/X+n3wBvpgSWqzmRkQdV+LeVIypQ52D3ZploZzbV6c/VdolAf1GNAtEEPc8rgaOq/P5jGx1Cz92+0kFcbBLr6XZ6CEuh8Uz+cof2u9AMsCwXA+uymdDR7O0jIhccCAwEAAaNVMFMwUQYDVR0RAQH/BEcwRYJDcHpobzlJRDVIRUZMaU9kejR6NDdNdWlqQnpRUGx5VzZLbVV4dVNTaS5zZWxmLXNpZ25lZC5nb2F1dGhlbnRpay5pbzANBgkqhkiG9w0BAQsFAAOCAgEAFf5qBwPYX1mzD4QkXjyi8yxoGONtlxseziDFAu/OVrLi34fQ6P9Ftuor95f1bkwLFgfidKZ7AMg2r2wml7ug6nhkETNss22qIG8amQuYQNWOAtG8Va2B0oHO/tlr8j5KePzZ2PabkJlPfyQ3YZTgjm6ExDKC5ARj8YETBJPA+Fywo/CVnXmUP8vCRm5eDSpvZcdAbcZ4eyDsgy17Pr5upFf4ctfPm9XR5/Qm7R/6XR927M2GttWKa3uqpcRiLlNpPVT8CVZkrHuhK9L+OKxOU0hv7pfkfYDPdl9tdj9M6Au0XmevtLEnQNay7XlJWw89otiySsH4vFAN286aa40qYwjC23/AVICEuq+UqZAh3d4+cXBjUWb1sWOAtpIeATE4rlgFDkZVYkcu6xRVlg6Z3mKmNFeGb434jsC6GbgikWSsRkSWqT6gdvLb+ieQlFBxlD1IrKHUYHqxrprsSXPlMCTA13KvrKb53/lAYBJ6n+NKK21Iejaek+k7tgSB4wFOUP3rVSUD4v0YbuZKlJG1scJfXmtSlwBSp8u2h0Yin83W5vmKCTx5AT+XpDZhzHSim3ABwot5VgqylQ6d0iCrMkxZcT6HSNo4u7mZQHANF48QhG4iN5FVZNnkNxZOacrTTQiFYwZp5Ub7Og2/maMEUELxRGEehs569jsL3tCY+PE=</ds:X509Certificate></ds:X509Data></ds:KeyInfo></md:KeyDescriptor><md:SingleLogoutService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect" Location="https://auth.cps.unileoben.ac.at/application/saml/rancher/slo/binding/redirect/"/><md:SingleLogoutService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="https://auth.cps.unileoben.ac.at/application/saml/rancher/slo/binding/post/"/><md:NameIDFormat>urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress</md:NameIDFormat><md:NameIDFormat>urn:oasis:names:tc:SAML:2.0:nameid-format:persistent</md:NameIDFormat><md:NameIDFormat>urn:oasis:names:tc:SAML:1.1:nameid-format:X509SubjectName</md:NameIDFormat><md:NameIDFormat>urn:oasis:names:tc:SAML:2.0:nameid-format:transient</md:NameIDFormat><md:SingleSignOnService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect" Location="https://auth.cps.unileoben.ac.at/application/saml/rancher/sso/binding/redirect/"/><md:SingleSignOnService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="https://auth.cps.unileoben.ac.at/application/saml/rancher/sso/binding/post/"/></md:IDPSSODescriptor></md:EntityDescriptor>

# Service Provider cert/key used by Rancher for SAML exchanges
spCert: |-
  -----BEGIN CERTIFICATE-----
  MIIE6zCCAtOgAwIBAgIQFlCJ13+RT0uPt1cgGASjVzANBgkqhkiG9w0BAQsFADAe
  MRwwGgYDVQQDDBNhdXRoZW50aWsgMjAyNS4xMC4yMB4XDTI2MDExODEzMDUzOFoX
  DTI3MDExOTEzMDUzOFowRTEZMBcGA1UEAwwQcmFuY2hlci1zYW1sLWtleTESMBAG
  A1UECgwJYXV0aGVudGlrMRQwEgYDVQQLDAtTZWxmLXNpZ25lZDCCAiIwDQYJKoZI
  hvcNAQEBBQADggIPADCCAgoCggIBAMcEeVUyySb5Doa53bM4h8gBzTo0Ms55vIjV
  e9qf553h8YrIeivDKwLeoKm8Ms+qACyu2xQD31I2PPnQeQUxbOzbc4QBchTIBy1m
  ttRuCtUxGg+wr31xHo4qIBmbtlBE44/iCtex4DhUyiRwFsC3gczQvzcSIw16yvKQ
  KiLa6qYvf8l3q5YknvpwRyqBb58+fbB8SGaXw+XYZ4bjQ3WcIvniwcUNi/uGJyfy
  dcN2WSBZg0Y/CL2q3IVLWaaxpFHjdk3+7rGBcKDnr1yWdLMx0dddQjDNi2NJuS6E
  +sI041kGbPjQw4uev9AeK0qZqUbINNQsZu90OYO6Q5airzNPbgjqVungBxjUwLwb
  0cYRCVqiYlsPZBXGuf+e49zqZqI6IOC+AC/0LoOQnvm2/stF9b4SlSdwJx58wSNB
  9/r5Hy6t0MM2YpTLCAKpm52SX7yq7jx6S5UkaX2521n/6m5Rm5RfD1c862sdnsbc
  /8u+h5jMr5HqTu2L/flND8okuoph1OAkS2CFqzebRvLP4g+1nxfMx7fjVlvRZDKf
  qX2SBObnzPTzvxGs7niyXM4SLRd4ZMmhi6vhEM7Q0+/f8LecqgqFbga8jMRVTj7v
  N5fIh6My4TDsJymM/ZoXv4YmP5pCkeVFX+yixr+HZaksbdBmAHFLVDRBPwmv2xak
  8L2AtGCPAgMBAAEwDQYJKoZIhvcNAQELBQADggIBAKlJODvBweQv6s9M8jkc0dC5
  Fms3qpZasJ2Exs+VssrpsSWO9VE2AE+1gu1K858Pk16Lk25v5xM/yv9iy04lUoFC
  1ctqjei3HLtUEutGB+HaCvPgXF1w3DuEscHEB/Kol9Q5nxL+BfsO4ZcHlcLjFPga
  65BzJ0PnsT4CvMW0AmvNyqM0HlvcLy7zCds8EFwYjiXTJ2bwNEOd4JwLaZHXwPsp
  j79AlYARKYFPWfoFlQ4qmVsJis18viFNTd5f2CED/Zn9lGjBLUiW7AurZoO1XEi+
  DEcG3A51tzVH8eMnooHwSYlrWsCdb+FekkdZvY9qkgjSTOkjYrz7riBrWwWmawfA
  em2jOBCQqpNVL+bvJmckzoNXwteC+DNXH3VOVKdOZqUjlplB3vzcmLHeQEAMb8v0
  Q/d+46rWYO0m2/79PRB9CKTaiA2edwECjYUH1HOK4YwfJ9kdTD/RAfL6YtQbLVPY
  NEYJFLFfzF+w5NYt0Fmrmvkm8ttYBL+UjlynzOFWH6482yt+mJMhKX1wuL+HzEfa
  7HSt57y8SoI24C/ULR9dbsFwv2K3oZqJkvrxt/UCnZUYV1pVbzZE6Ab8HrqbQbeT
  FtcAYJrLLbn6vnYyyBn8CQy8Gee19oYjOk3uYCzo1otyuSA6496HVfc91FdUqCQS
  vBRVNFbTtQahPnXFDSU7
  -----END CERTIFICATE-----c

spKey: |-
  -----BEGIN RSA PRIVATE KEY-----
  MIIJKAIBAAKCAgEAxwR5VTLJJvkOhrndsziHyAHNOjQyznm8iNV72p/nneHxish6
  K8MrAt6gqbwyz6oALK7bFAPfUjY8+dB5BTFs7NtzhAFyFMgHLWa21G4K1TEaD7Cv
  fXEejiogGZu2UETjj+IK17HgOFTKJHAWwLeBzNC/NxIjDXrK8pAqItrqpi9/yXer
  liSe+nBHKoFvnz59sHxIZpfD5dhnhuNDdZwi+eLBxQ2L+4YnJ/J1w3ZZIFmDRj8I
  varchUtZprGkUeN2Tf7usYFwoOevXJZ0szHR111CMM2LY0m5LoT6wjTjWQZs+NDD
  i56/0B4rSpmpRsg01Cxm73Q5g7pDlqKvM09uCOpW6eAHGNTAvBvRxhEJWqJiWw9k
  Fca5/57j3Opmojog4L4AL/Qug5Ce+bb+y0X1vhKVJ3AnHnzBI0H3+vkfLq3QwzZi
  lMsIAqmbnZJfvKruPHpLlSRpfbnbWf/qblGblF8PVzzrax2extz/y76HmMyvkepO
  7Yv9+U0PyiS6imHU4CRLYIWrN5tG8s/iD7WfF8zHt+NWW9FkMp+pfZIE5ufM9PO/
  EazueLJczhItF3hkyaGLq+EQztDT79/wt5yqCoVuBryMxFVOPu83l8iHozLhMOwn
  KYz9mhe/hiY/mkKR5UVf7KLGv4dlqSxt0GYAcUtUNEE/Ca/bFqTwvYC0YI8CAwEA
  AQKCAgAg54T2CKkIWApGTSmyDYkpkN6xHls+FxOMXhuVqHV/fZFVfFLytFiCp3NR
  zOtruTRBLwHKu98q9Qu80/KGYMcdHCVrsF9/vxissXxOAAmreOxRpslFCLRgFefr
  w/pvKAylx946Dk8/kQlA4AVrBIwh5GuQ+98uxdwTIbHNxHsiUd0jXrVQZCqixniF
  txPQ9OCMEuhXigUaFd78BswrAE8qGIsn/NbllacYrDY7RHB08EfLj/VugnbmVPB0
  Jo+/+EchmyI01+1atSOhv8B4tiZ3IJSmg/1lQ5Wp8tOQ03S5Td4rfzytc2hMTQik
  U2aQ7N4LLHIyafluZZfyKmCkL6BF7uhMnBgthBHxDeN+Y5N9yuVgi3doGn24WIkX
  YjytUUPF/TA+uv/kzqIT9HfVWSL78kfYtSiTztRVLu7YBGYxRMiF7tpKgbqfgteY
  eOu3KdIi83w0dY6wPHYS/yPgGG1V5CBP5WIRJdHkyjZUJf4BZSdSLYMpNFFirHw3
  O+Qx47OFf3p41nyeJn5mES9CDGfPWwGOIObCfEqOG6kANoNnZvWV/bWmsi0k4Oj+
  kztnSfdFNGH6hP8RcT4/4jFjoDJgTYb4keYZ+1okMitJ3XBlX9IZENETq/3gx6X7
  PqVmN8UQ3NbT/pgtsRTZsPlXVblSAxd2oF0PylQEWl5BSNDboQKCAQEA/mgDect5
  1kiO/YnCpQ5RdmTnDY5lOJTFWT2UvrWnkp2rEvuN4jvV6JZ4LH0XYZaVq9RN1N9a
  9iZeawuCiQlYrncGCaL8pP3I1hvFopVEDrIFhaJX8VI4aI+bgvqMTfiKM6B41nQ3
  yVKBEGRqFYgFlW0Rk6cGK0W5qIxbvWrH/Ql3CUpNyHWaevh1FrcQRcObynUNhM9u
  EYF6DM5WuJSdOrse2hhha9LdQvXA0siLgL3ahJ4oZjVw1vj44saRvh8iOhGhYqJC
  r62rm89/4iW8KTNfehZAAl65XKMaPeNm+pF6KTpgKom8DvBNjEfOwbaBTFsYIlDZ
  JLFQQHaVwRbOLwKCAQEAyEOiZ/Zt+db5CecXwBeXTAXgkpGrK8JJHXCCzYExtFPY
  YapfJ8aGnRvglmhJEU/54yM0nSzs5a8rcPD16PaHBynzPvV0Bh47QaEyMBKrmzNN
  HTMfOUcGHUabPqZmenErYIESdKRidEBNsBZn1K3kA18y+pzUdC96RhImqRmXCtoy
  HamvT1NkIzYhl3InaIlgs6NzmufzpJ7GXb39B+uL/2ISUOWzjeJrRa6Ud0faOE2o
  tCpjboiqYxfPiOf/0UnRUgFTt6wEs6V6DOgoU5NqT5DCw5WYrgLhZ1Ovc5XEtRaT
  lWcgcQEyjRU9n+lT0ssDRuQvD6nfDFTRPVOF6I5boQKCAQBcLNF9knSdaAKu5/fn
  F636SIrShZI1EuoB8GbxRh3l6Exwf0Yj/uv87m+yJsyO5iFqdWyRwS9S2goBnNT5
  07IW3DcKzMve97iJotxTkONss6F+jphwbgrUD5wXs7GcGn3wQKcnhEomHkd26frp
  vDPRtQfWSIDastOWtuwSUBsPmhtP+WT/SWTkQxshVMiHjlzm2MxCH2nQ2+mdtDEF
  hYsGGYAPIyBBEdBrD2GCvXiV97OxsyAOEDTHHsQGXk215c/f3D1t4D5rKnBv7pl2
  FZf8EYn5URB2C137q3i5jaflB0qMn4LyRp8lhnmCZw4Jb5efU64F2Ocj/T6HbK/L
  mvivAoIBAQCzUSxInrWWslDH9y6jB/ynS9PsKZb1VcAWJjpZPMd+ylzEBsOxX+gF
  IYMV6kcSw2PjaBCidCmi+BiTxo7KjIQXfA6cXzgGimdQur+vn+gczfDMpovcw6XL
  7P7xOBompNLMVIZr/w1RPorRkx5hp1q1UjbZhDgP2LtJptMLMyi1xO5+9QNOqkLN
  7JhjfQmgZvI5p6/KEstsqebA5W99+gGfKPdxjFwcPZMED/BMZgAVziOzPwlNXf4D
  QLzJv8KmacyN+zY1Dkgfe5ovmGkTfLoCiIJ8kqTlmxqtZJeDjaVW6OI5MuAvj3zu
  KwjE+S3fX3yNq6AgDGD2L7Qzj2gl9eJBAoIBAH4a/WsV13In6WSv8o+pGKmXVAfl
  Dj3QB2B/SmL8aEayoA+hS9Mj8stae2wBi16qGe+n72XuZGVoOGuQIsE8jd/EYKoc
  CrcP0BkoftBOOsraB/y64XH3RiHFEggk2fYR47ASrJLExd1GsKx4qTx1DngOKoMb
  y7Dtqma2jWJVAXtMxf8fH6fm/54ofl6tiXxrzsQGLZ20N2PWY81Z4kL2rZ4w/y64
  9xnMgJuNpQAXkb9CAAekoXA8SZEXCet0ZHaeWHFne9aZid6GeHk8Ggfz+OgHME+Q
  fgL6iz9gVmKnzCVgaHN+x8DQQhp3+JwFT8A47qQDPyMjR41npVH1NIeYOKk=
  -----END RSA PRIVATE KEY-----
