apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: harbor-admin-password
    namespace: harbor
spec:
    secretTemplates:
        - name: harbor-admin-password
          stringData:
            HARBOR_ADMIN_PASSWORD: ENC[AES256_GCM,data:nlMkh5O+C67rxWjELojpJVbZMH8OwhECF+gudGtxmQ==,iv:0Pr2ca6neGKguGfQvbvjxOHyGdM0ac6yu+D9V6/DtII=,tag:+h7J6LblvLYMPRPWCc99qQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZZUJLNThHeE9GajNVZjYy
            NU85a0Jod1hEeGZ5bkw3L0ZKU0tPYnpDc0FZClNJU2crRXNCSnNQM0M0VkFGZ3dB
            QXdtMkJEYUVJNmJUVFpGSzhnZFE0cU0KLS0tIHBUUzhYQXlKbDRGdW9zY0VRY29y
            YkxUUGtPUkFhRWtzREZwbDlJc2VFNG8Ktakqq5g3h9QDk32m9rLt1/TIDkIUIicd
            gNW4kF30Oh73rtAGBXp9VCW/E8yJW/qSOELvlOaUFXJ9tyuXz2dzjQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h05qj66un22scwapuhyl76skls7ll235vlu27cjwkk5tpav6sqmsx3zp6a
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-07-24T21:48:35Z"
    mac: ENC[AES256_GCM,data:THHQpV6PRadJAcIMuIbpgA76rp84hByfnQvSBChfAhbJL37BEguHxZHzRhgmOUXbE92huhLTs0vCHf/grsyfchRbn5sVaRuRMRIFVr9WWE/j9UwnyifMFLLcP56qoJhUMs04aEpbvpSKLrlR19I/gxJ4EQAaPJQmTv3xYnNgVso=,iv:Mq0enTOm05GcS+3FGJq3eej0fC0qeH0KgthXvYCvu1Q=,tag:BKh7Tw7nQYVeiRoEAR5c2A==,type:str]
    version: 3.13.3
