apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: harbor-secret-key
    namespace: harbor
spec:
    secretTemplates:
        - name: harbor-secret-key
          stringData:
            secretKey: ENC[AES256_GCM,data:uo2VzbNctEi/fiezugaoxA==,iv:bsE4CxlrAbE9nAdmxLDpzJg5vFu5ioTghB4su/CKR6Y=,tag:ary33oxE6qQX6E4kovVn3A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtUmJUZzBySG16cGkyUEsw
            d3FUZlVUVEFtMHdWRWxpb3Fqa2w4RVBJNjNvCjBFYmJOM3pPSjJaQnlyalZhVTFy
            R3VsK1h0bUJVRWc3Sy90d1VyZE42bzAKLS0tIEYzT1JKeU1oUmZpQ1piODkxaTZX
            OUwrZDFKVDFJanlpVkZMZG1hYlZXQ2sKcuYk6FGB+q6poWrPGsugWg9+amfwSQRU
            SRs3VEjXZAmQQy7Ncmvv4/6ld7dGLW491Qh38PubwOpr+XtevKOONA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h05qj66un22scwapuhyl76skls7ll235vlu27cjwkk5tpav6sqmsx3zp6a
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-07-24T21:48:35Z"
    mac: ENC[AES256_GCM,data:RYdU36YJhDx7vh20Wy3IhrB/x+fry5fjHGri63isB5LVD2LcqpQe6tEtHLcr+WTommZrsyiSXcK4Am6Rnxbe8jVxZTpBFK33ptqkPblUajtYH0G6/xzSgAQYYPe4YbG/dk+fZoS59LnTp7wlDaR0mrE1Z0IB+LCIY/N23H4Y+J8=,iv:NqbE8lu5fvQVUwaPb52Utb6N32TFI4dymKCI8ci+IrU=,tag:+b69rW9gSgnfHQ49YJ2tXg==,type:str]
    version: 3.13.3
